# Generated by Django 5.2.4 on 2025-07-25 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'İletişim Mesajı', 'verbose_name_plural': 'İletişim Mesajları'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inquiry_type',
            field=models.CharField(choices=[('calisma_izni', 'Çalışma İzni'), ('ikamet_izni', 'İkamet İzni'), ('vatandaslik', 'Vatandaşlık'), ('saglik_sigortasi', 'Sağlık Sigortası'), ('genel', 'Genel Danışma')], default='genel', max_length=20, verbose_name='Hizmet Türü'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_responded',
            field=models.BooleanField(default=False, verbose_name='Yanıtlandı mı?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Konu'),
        ),
    ]
